### ISSUE TITLE
CF Worker to refresh KV store content on a nightly basis

### ISSUE THREAD

**Issue by richardhunghhw** [hungrytapirldn/hungrytapirldn.com#2]
- https://developers.cloudflare.com/workers/runtime-apis/scheduled-event/
- Cron expression TEST `0 23 * * *`, PROD `0 5 * * *` UTC time
- API path at `app/routes/api.refresh-content.tsx`
- Worker should be named `refresh-trigger` under the `workers` dir
- Promote worker to TEST and PROD envs 
- By default, do not supply purge param, but allow config through env

**Comment by michelle-lai-swl** [comment]
Hey, if you have time, could you please take a look at these two runs? I've modified the workflow files to use cron scheduling since the run (can view on branch) but it won't be running until tonight (i'm guessing)?

https://github.com/richardhunghhw/hungrytapir-store/actions/runs/5560630929
https://github.com/richardhunghhw/hungrytapir-store/actions/runs/5560630924

I spent a lot of time trying to make a reusable workflow so that it could call the common workflow until I realised that reusable workflows can't be chained :/ Let me know if you have any suggs on making it cleaner or adding the purge thing - I'll check again tonight

**Comment by richardhunghhw** [comment]
Structure looks fine but don't want to rely on separate files for each env. Use the branch SETENV strategy in the other workflow files and derive the env from there. Then load the url from `hostname` field `op://${{ vars.VAULT_NAME }}/HT Basic/hostname`, will have to load the production hostname from a different vault so let me have a think about how to arrange that. 

In terms of purge, best to use an environment variable to control that as well, you should be able to default it to ?purge=false for now.

> Hey, if you have time, could you please take a look at these two runs? I've modified the workflow files to use cron scheduling since the run (can view on branch) but it won't be running until tonight (i'm guessing)?
> 
> 
> 
> https://github.com/richardhunghhw/hungrytapir-store/actions/runs/5560630929
> 
> https://github.com/richardhunghhw/hungrytapir-store/actions/runs/5560630924
> 
> 
> 
> I spent a lot of time trying to make a reusable workflow so that it could call the common workflow until I realised that reusable workflows can't be chained :/ Let me know if you have any suggs on making it cleaner or adding the purge thing - I'll check again tonight
